### PR TITLE
Delete asdf

### PR DESCRIPTION
**Pull request by brandon-leapyear**
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:

---

### CODE REVIEW

**Review by brandonchinn178 — CHANGES_REQUESTED** [review]
boo

**Review by brandonchinn178 — APPROVED** [review]

**Review by brandonchinn178 — DISMISSED** [review]
meh

**Review by brandonchinn178 — COMMENTED** [review]
f

**Review by jeff-hammel-leapyear — CHANGES_REQUESTED** [review]
I don't know about any of this.  I kinda like asdf

**Review by jeff-hammel-leapyear — APPROVED** [review]
Okay, you're right.  While ASDF is kinda awesome, this file isn't the right place for it

**Review by brandonchinn178 — CHANGES_REQUESTED** [review]
nope

**Review by brandonchinn178 — APPROVED** [review]

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

I just posted a comment!

**Comment by jeff-hammel-leapyear** [comment]
> I just posted a comment!

So, I'm kinda in suspense.  My own project, leftpad, makes heavy use of `asdf`;  should I fork it? Or will this be maintained.  I'm kinda okay with a sunset period, I guess....so that I can develop my own in-house (I've actually been wanting to do this for awhile).  But if this disappeared tomorrow, production would fall over!

**Pull request closed without merging**
